/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jd_dtc_api_Request */

#ifndef _Included_com_jd_dtc_api_Request
#define _Included_com_jd_dtc_api_Request
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_dtc_api_Request
 * Method:    InitRequest
 * Signature: (Lcom/jd/dtc/api/Server;I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_InitRequest
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    DestroyRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_DestroyRequest
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_Reset__
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Reset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_Reset__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    AttachServer
 * Signature: (Lcom/jd/dtc/api/Server;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_AttachServer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    NoCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_NoCache
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    NoNextServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_NoNextServer
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request////
 * Method:    Need
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Need__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Need
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Need__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    FieldType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_FieldType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Limit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_Limit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    UnsetKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Request_UnsetKey
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    SetKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_SetKey__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    SetKey
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_SetKey__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    AddKeyValue
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_AddKeyValue__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    AddKeyValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_AddKeyValue__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    AddKeyValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_AddKeyValue__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    SetCacheID
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_SetCacheID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    JExecute
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Request_JExecute__
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    JExecute
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Request_JExecute__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    JExecute
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Request_JExecute__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    JExecute
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Request_JExecute__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Execute
 * Signature: (Lcom/jd/dtc/api/Result;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Execute__Lcom_jd_dtc_api_Result_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Execute
 * Signature: (Lcom/jd/dtc/api/Result;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Execute__Lcom_jd_dtc_api_Result_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Execute
 * Signature: (Lcom/jd/dtc/api/Result;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Execute__Lcom_jd_dtc_api_Result_2Ljava_lang_String_2
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Execute
 * Signature: (Lcom/jd/dtc/api/Result;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Execute__Lcom_jd_dtc_api_Result_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    ErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Request_ErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    EQ
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_EQ__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    EQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_EQ__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    EQ
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_EQ__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    NE
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_NE__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    NE
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_NE__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    NE
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_NE__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    GT
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_GT
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    GE
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_GE
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    LE
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_LE
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    LT
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_LT
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    OR
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_OR
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Add
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Add__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Add
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Add__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Sub
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Sub__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Sub
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Sub__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Set
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Set__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Set
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Set__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Set
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Set__Ljava_lang_String_2Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Set
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Set__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    Set
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_Set__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    CompressSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_CompressSet
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    CompressSetForce
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_CompressSetForce
  (JNIEnv *, jobject, jstring, jstring, jlong);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    SetMultiBits
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Request_SetMultiBits
  (JNIEnv *, jobject, jstring, jint, jint, jint);

/*
 * Class:     com_jd_dtc_api_Request
 * Method:    GetCurrentUSeconds
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Request_GetCurrentUSeconds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
