/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jd_dtc_api_Server */

#ifndef _Included_com_jd_dtc_api_Server
#define _Included_com_jd_dtc_api_Server
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jd_dtc_api_Server
 * Method:    InitServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_InitServer
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetTableName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_SetTableName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    DestroyServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_DestroyServer
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetAddress
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_SetAddress
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    CloneTabDef
 * Signature: (Lcom/jd/dtc/api/Server;)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_CloneTabDef
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    CloneServer
 * Signature: (Lcom/jd/dtc/api/Server;)J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Server_CloneServer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetCompressLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetCompressLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    GetAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Server_GetAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    GetTableName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Server_GetTableName
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    GetServerAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Server_GetServerAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    GetServerTableName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Server_GetServerTableName
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    IntKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_IntKey
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    BinaryKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_BinaryKey
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    StringKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_StringKey
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    AddKey
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_AddKey
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    FieldType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_FieldType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    ErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jd_dtc_api_Server_ErrorMessage
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetMTimeout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetMTimeout
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    Connect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_Connect
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    Ping
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_Ping
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    AutoPing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_AutoPing
  (JNIEnv *, jobject);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetFD
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetFD
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetAutoUpdateTab
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetAutoUpdateTab
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetAutoReconnect
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetAutoReconnect
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    CheckPacketSize
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jd_dtc_api_Server_CheckPacketSize
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    SetAccessKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jd_dtc_api_Server_SetAccessKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jd_dtc_api_Server
 * Method:    GetCurrentUSeconds
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jd_dtc_api_Server_GetCurrentUSeconds
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
