include ../../Make.conf

################compile#############
target = key-hash.so

CFLAGS += -DDEBUG

key-hash_objs := KeyHash.o

###############install##############
target_install = key-hash.so 
install_dir = ../../../lib

include ../../Make.rules
