include ../Make.conf
target_install = cache.conf hbp.conf table.conf agent.xml crontab.xml agent.conf plugin.conf contacts.xml dtchttpd_example.conf dtcalarm.conf prober.xml monitor.conf
install_dir = ../../conf
include ../Make.rules
